### ISSUE TITLE
[02-kde.sh] kdebase-konqueror kdebase-konq-plugins deprecated

### ISSUE THREAD

**Issue by webnux** [xp-1000/Arch-install#3]
You should replace : 

`yaourt -Rsn --noconfirm kdebase-konqueror kdebase-konq-plugins kate `

by 

`yaourt -Rsn --noconfirm konqueror kate`

in 02-kde.sh

**Comment by xp-1000** [comment]
hello,
Now I use meta package so we did not have to uninstall this.
it should be ok now.
